var number1 = 4;
console.log("The first number: ", number1);
var number2 = -50;
console.log("The second number: ", number2);
var number3 = 0;
console.log("The third number: ", number3);
var number4 = 32.564;
console.log("The fourth number: ", number4);
var string1 = "Hello";
console.log("The first string: ", string1);
var string2 = "World";
console.log("The second string: ", string2);
var string3 = "!?";
console.log("The third string: ", string3);
var boolean1 = true;
console.log("The first boolean: ", boolean1);
var boolean2 = false;
console.log("The second boolean: ", boolean2);
var undefined1;
console.log("The undefined variable: ", undefined1);
